/**
 * Cookie 导入/导出 CLI（一次性 CDP 连接）
 * 用法:
 *   node dist/cookies_cli.js --cdp-url=http://127.0.0.1:PORT --mode=export
 *   node dist/cookies_cli.js --cdp-url=http://127.0.0.1:PORT --mode=import --payload='...'
 *   node dist/cookies_cli.js --mode=parse --payload='...'   # 仅解析 Netscape/JSON → Playwright 格式
 *
 * 仅通过 stdout 输出 JSON 行，禁止纯文本打印。
 */
import { chromium } from "playwright-core";

import { installIpcGuards } from "./json-logger.js";

installIpcGuards();

export interface CloakCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires: number;
  httpOnly: boolean;
  secure: boolean;
  sameSite: "Strict" | "Lax" | "None";
}

function emit(payload: Record<string, unknown>): void {
  process.stdout.write(`${JSON.stringify(payload)}\n`);
}

function readArg(argv: string[], name: string): string | undefined {
  const prefix = `--${name}=`;
  const hit = argv.find((arg) => arg.startsWith(prefix));
  if (hit) {
    return hit.slice(prefix.length);
  }
  const index = argv.indexOf(`--${name}`);
  if (index >= 0 && argv[index + 1]) {
    return argv[index + 1];
  }
  return undefined;
}

async function readPayload(argv: string[]): Promise<string> {
  const inline = readArg(argv, "payload");
  if (inline !== undefined) {
    return inline;
  }
  const filePath = readArg(argv, "payload-file");
  if (filePath) {
    const { readFile } = await import("node:fs/promises");
    return readFile(filePath, "utf8");
  }
  return "";
}

function normalizeSameSite(raw: unknown): "Strict" | "Lax" | "None" {
  const value = String(raw ?? "Lax").toLowerCase();
  if (value === "strict") {
    return "Strict";
  }
  if (value === "none") {
    return "None";
  }
  return "Lax";
}

function normalizeCookie(raw: Record<string, unknown>): CloakCookie | null {
  const name = String(raw.name ?? "").trim();
  const value = String(raw.value ?? "");
  const domain = String(raw.domain ?? "").trim();
  if (!name || !domain) {
    return null;
  }
  const expiresRaw = raw.expires ?? raw.expirationDate ?? -1;
  let expires = Number(expiresRaw);
  if (!Number.isFinite(expires)) {
    expires = -1;
  }
  // Playwright: -1 = session；秒级时间戳
  if (expires > 1e12) {
    expires = Math.floor(expires / 1000);
  }
  return {
    name,
    value,
    domain,
    path: String(raw.path ?? "/").trim() || "/",
    expires,
    httpOnly: Boolean(raw.httpOnly),
    secure: Boolean(raw.secure),
    sameSite: normalizeSameSite(raw.sameSite),
  };
}

/** 解析 Playwright JSON 数组或 Netscape cookie 文本 */
export function parseCookiePayload(raw: string): CloakCookie[] {
  const trimmed = raw.replace(/^\uFEFF/, "").trim();
  if (!trimmed) {
    return [];
  }

  if (trimmed.startsWith("[") || trimmed.startsWith("{")) {
    const parsed = JSON.parse(trimmed) as unknown;
    const list = Array.isArray(parsed)
      ? parsed
      : Array.isArray((parsed as { cookies?: unknown }).cookies)
        ? ((parsed as { cookies: unknown[] }).cookies)
        : null;
    if (!list) {
      throw new Error("JSON Cookie 格式无效：需要数组或 { cookies: [] }");
    }
    return list
      .map((entry) =>
        entry && typeof entry === "object"
          ? normalizeCookie(entry as Record<string, unknown>)
          : null,
      )
      .filter((entry): entry is CloakCookie => entry !== null);
  }

  // Netscape / curl cookie jar
  const cookies: CloakCookie[] = [];
  for (const line of trimmed.split(/\r?\n/)) {
    const text = line.trim();
    if (!text || text.startsWith("#")) {
      continue;
    }
    const parts = text.split("\t");
    if (parts.length < 7) {
      continue;
    }
    const [domain, , path, secure, expiresStr, name, ...valueParts] = parts;
    const value = valueParts.join("\t");
    const expires = Number(expiresStr);
    cookies.push({
      name: name.trim(),
      value,
      domain: domain.trim(),
      path: (path || "/").trim() || "/",
      expires: Number.isFinite(expires) && expires > 0 ? expires : -1,
      httpOnly: false,
      secure: String(secure).toUpperCase() === "TRUE",
      sameSite: "Lax",
    });
  }
  return cookies;
}

function toNetscape(cookies: CloakCookie[]): string {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by CloakForge"];
  for (const cookie of cookies) {
    const expires =
      cookie.expires > 0 ? String(Math.floor(cookie.expires)) : "0";
    lines.push(
      [
        cookie.domain,
        cookie.domain.startsWith(".") ? "TRUE" : "FALSE",
        cookie.path || "/",
        cookie.secure ? "TRUE" : "FALSE",
        expires,
        cookie.name,
        cookie.value,
      ].join("\t"),
    );
  }
  return `${lines.join("\n")}\n`;
}

async function exportCookies(cdpUrl: string, format: string): Promise<void> {
  const browser = await chromium.connectOverCDP(cdpUrl);
  try {
    const context = browser.contexts()[0];
    if (!context) {
      throw new Error("CDP 未找到 BrowserContext");
    }
    const raw = await context.cookies();
    const cookies = raw
      .map((entry) => normalizeCookie(entry as unknown as Record<string, unknown>))
      .filter((entry): entry is CloakCookie => entry !== null);

    if (format === "netscape") {
      emit({
        type: "cookie_export",
        format: "netscape",
        count: cookies.length,
        text: toNetscape(cookies),
      });
    } else {
      emit({
        type: "cookie_export",
        format: "json",
        count: cookies.length,
        cookies,
      });
    }
  } finally {
    await browser.close().catch(() => undefined);
  }
}

async function importCookies(cdpUrl: string, payload: string): Promise<void> {
  const cookies = parseCookiePayload(payload);
  if (cookies.length === 0) {
    throw new Error("未解析到任何 Cookie");
  }
  const browser = await chromium.connectOverCDP(cdpUrl);
  try {
    const context = browser.contexts()[0];
    if (!context) {
      throw new Error("CDP 未找到 BrowserContext");
    }
    await context.addCookies(cookies);
    emit({
      type: "cookie_import",
      count: cookies.length,
      ok: true,
    });
  } finally {
    await browser.close().catch(() => undefined);
  }
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const mode = (readArg(argv, "mode") ?? "").trim().toLowerCase();
  const cdpUrl = readArg(argv, "cdp-url")?.trim();
  const format = (readArg(argv, "format") ?? "json").trim().toLowerCase();
  const payload = await readPayload(argv);

  try {
    if (mode === "parse") {
      const cookies = parseCookiePayload(payload);
      emit({ type: "cookie_parse", count: cookies.length, cookies });
      return;
    }
    if (mode === "export") {
      if (!cdpUrl) {
        throw new Error("export 需要 --cdp-url");
      }
      await exportCookies(cdpUrl, format);
      return;
    }
    if (mode === "import") {
      if (!cdpUrl) {
        throw new Error("import 需要 --cdp-url");
      }
      await importCookies(cdpUrl, payload);
      return;
    }
    throw new Error(`未知 mode: ${mode || "(empty)"}`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    emit({ type: "error", kind: "error", message });
    process.exitCode = 1;
  }
}

void main();
